config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  get 'users/destroy'
  get 'users/index'
  root to: 'ideas#index'

  devise_for :users

  resources :ideas do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:edit, :update]
  resources :bookings, only: [:show] do
    resources :reviews, only: [:new, :create]
  end
  resources :bookings do
    member do
      patch :accept
      patch :decline
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  has_many :reviews

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :request_message, presence: true, length: { minimum: 10 }
end




#comment

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :category, presence: true
  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch
  pg_search_scope :search_by_title_and_category_and_description,
                  against: [:title, :category, :description],
                  using: {
                    tsearch: {
                      prefix: true
                    }
                  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :comment, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, allow_blank: false, numericality: {only_integer: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?


  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end



  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    skip_after_action :verify_authorized
    skip_after_action :verify_policy_scoped
    before_action :set_booking, only: [:edit, :show, :update, :accept, :decline]

  def new
    @idea = Idea.find(params[:idea_id])
    @booking = Booking.new(idea: @idea)
  end

  def create
    @idea = Idea.find(params[:idea_id])
    @booking = Booking.new(booking_params)
    @booking.idea = @idea
    @booking.user = current_user
      if @booking.save
        redirect_to users_show_path, anchor: "home"
      else
        render :new
    end
  end

  def accept
    @booking.validated = true
    @booking.save
    redirect_to users_show_path, anchor: "home"
  end

  def decline
    @booking.validated = false
    @booking.save
    redirect_to users_show_path, anchor: "home"
  end

  def show
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :request_message, :validated)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_idea, only: [:update, :show, :edit, :destroy]

  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def new
    @idea = Idea.new
    authorize @idea
  end

  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user

    if @idea.save
      redirect_to idea_path(@idea)
    else
      render :new
    end
  end

  def edit
    authorize @idea
  end

  def update
    authorize @idea
    if @idea.update(idea_params)
      redirect_to idea_path(@idea)
    else
      render :edit
    end
  end

  def show
    @marker =
      [{
        lng: @idea.longitude,
        lat: @idea.latitude
      }]
    # @marker = @marker.select do |e|
    #   e[:lng] || e[:lat]
    # end
  end

  def index
    @cat = [
      'Arts, crafts, and collectibles',
      'Beauty and fragrances',
      'Books and magazines',
      'Education',
      'Electronics and telecom',
      'Entertainment and media',
      'Food retail and service',
      'Gifts and flowers',
      'Government',
      'Health and personal care',
      'Home and garden',
      'Pets and animals',
      'Services - other',
      'Sports and outdoors',
      'Travel',
      ]

    if params[:query].present?
      @ideas_pre = Idea.search_by_title_and_category_and_description(params[:query])
    else
      @ideas_pre = Idea.all
    end

    @ideas = []

    @ideas_pre.each do |idea|
      c1 = params[:category].present? && idea.category ? idea.category == params[:category] : true
      c2 = params[:max_price].present? && idea.pricing ? idea.pricing < params[:max_price].to_i : true
      c3 = true
      idea.bookings.to_a.each do |b|
        if params[:start_date].present? && params[:end_date].present?
          c3 = false if b.start_date < Date.parse(params[:end_date]) && b.end_date > Date.parse(params[:start_date])
        end
      end
      @ideas << idea if c1 && c2 && c3
    end

    @markers = @ideas.map do |idea|
      {
        lng: idea.longitude,
        lat: idea.latitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { idea: idea })
      }
    end
    @markers = @markers.select do |e|
      e[:lng] || e[:lat]
    end
  end

  def destroy
    authorize @idea
    @idea.destroy
    redirect_to ideas_path
  end

  private

  def set_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
     params.require(:idea).permit(
      :user_id,
      :title,
      :description,
      :category,
      :revenue_model,
      :pricing,
      :start_date,
      :end_date,
      :minimum_duration,
      :application_criteria,
      :photo,
      :photo_cache
      )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    if @review.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  skip_before_action :authenticate_user!, only: :index
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def show
    @ideas = Idea.where(user_id: @user.id)
    @requests = Booking.joins(:idea).where(ideas: {user_id: @user.id} )
    @bookings = Booking.where(user_id: @user.id)
  end

  def edit

  end

  def update
  end

  def destroy
  end

  def index
  end

  private

  def user_params
    params.require(:user).permit(
      :id,
      :photo,
      :first_name,
      :last_name,:email,:description
      )
  end
  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/new.html.erb
<div class="container">
 <div class="formulaire">
  <div class="principale white-box">
      <%= simple_form_for [@idea, @booking] do |f| %>
      <p><%= @idea.title %></p>
      <div class="form-input-inline">
        <div class="mr">
      <%= f.input :start_date, as: :string, required: true, input_html: {class: "datepicker"}   %>
        </div>
        <div>
      <%= f.input :end_date, as: :string, required: true, input_html: {class: "datepicker-end"} %>
        </div>
      </div>
       <%= f.input :request_message, input_html: {value: f.object.request_message || 'I would like to book your idea. Have a good day'}%>
      <%= f.submit "Book this idea", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Booking of <%= @booking.idea.title %></h1>

<p>Innovator : <%= @booking.idea.user.first_name %> <%= @booking.idea.user.last_name %></p>
<p>Entrepreneur : <%= @booking.user.first_name %> <%= @booking.user.last_name %></p>
<p>Start date : <%= @booking.start_date %></p>
<p>End date : <%= @booking.end_date %></p>

<%= link_to 'Rate the idea', new_booking_review_path(@booking) %>

app/views/ideas/_form.html.erb
<div class="container">
  <div class="main-form">
    <%= simple_form_for @idea, :html => { :class => 'form-horizontal' } do |f| %>

      <%- if f.error_notification %>
        <div class="alert alert-error fade in">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          <%= f.error_notification %>
        </div>
      <%- end %>

      <div class="form-inputs">
        <div class="form-input-inline">
          <div class="form-component"> <%= f.input :title, label: "Idea title"%></div>
          <div> <%= f.input :category%></div>
        </div>
        <%= f.input :description, label: "How will this idea change the world?" %>
        <div class="form-input-inline">
        <div class="form-component"> <%= f.input :pricing, label: "Set a price per day" %></div>
        <%= f.input :minimum_duration, label: "What is the min duration?" %>
        </div>
        <%= f.input :application_criteria, label: "Application_criteria" %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden,label: "" %>

        <%= f.submit "add an Idea", class: "btn btn-primary btn-form" %>
      </div>
    <% end %>
  </div>
</div>












<!-- <div class="container">
  <div class="main-form">
    <%= simple_form_for @idea, :html => { :class => 'form-horizontal' } do |f| %>

      <%- if f.error_notification %>
        <div class="alert alert-error fade in">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          <%= f.error_notification %>
        </div>
      <%- end %>

      <div class="form-inputs">
        <div class="form-input-inline">
          <div class="form-component"> <%= f.input :title, label: "Idea title"%></div>
          <div> <%= f.input :category%></div>
        </div>
        <%= f.input :description, label: "How will this idea change the world?" %>
        <div class="form-input-inline">
        <div class="form-component"> <%= f.input :pricing, label: "Set a price per day" %></div>
        <%= f.input :minimum_duration, label: "What is the min duration?" %>
        </div>
        <%= f.input :application_criteria, label: "Application_criteria" %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden,label: "" %>

        <%= f.submit "add an Idea", class: "btn btn-primary btn-form" %>
      </div>
    <% end %>
  </div>
</div>
 -->

app/views/ideas/_infowindow.html.erb
<p><%= idea.title %></p>
<p><%= idea.category %></p>

app/views/ideas/_searchbar.html.erb
<div class="col-sm-10">
  <%= form_tag ideas_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control adding-border-radius",
      placeholder: "Find an idea"
    %>
  <% end %>
</div>

app/views/ideas/_searchform.html.erb
<div class="col-sm-12 col-sm-offset-0" style="margin-top: 60px;">
  <%= form_tag ideas_path, method: :get, class: "display-flex" do %>
    <div class="col-sm-2", style="display: flex; flex-direction: column; align-items: flex-start; margin-right: 8px; color: black;">
      <%= label_tag 'name' %>
      <%= text_field_tag :query,
        params[:query]
      %>
    </div>
    <div class="col-sm-2", style="display: flex; flex-direction: column;  align-items: flex-start; margin-right: 8px; color: black;">
      <%= label_tag 'category' %>
      <%= select_tag "category",
        options_for_select(@cat.push(''), params[:category] ? params[:category] : '')
      %>
    </div>
    <div class="col-sm-2", style="display: flex; flex-direction: column;  align-items: flex-start; margin-right: 8px; color: black;">
      <%= label_tag 'max price' %>
      <%= number_field_tag 'max_price',
        params[:max_price]
      %>
    </div>
    <div class="col-sm-2", style="display: flex; flex-direction: column;  align-items: flex-start; margin-right: 8px; color: black;">
      <%= label_tag 'start_date' %>
      <%= date_field_tag 'start_date',
          '01/01/2000'
      %>
    </div>
    <div class="col-sm-2", style="display: flex; flex-direction: column;  align-items: flex-start; margin-right: 8px; color: black;">
      <%= label_tag 'end_date' %>
      <%= date_field_tag 'end_date',
        '01/01/2000'
      %>
    </div>
    <div style="display: flex; flex-direction: column;  align-items: flex-start; margin-right: 8px; color: black;">
      <%= submit_tag "filter", class: 'btn btn-search' %>
    </div>
  <% end %>
</div>

app/views/ideas/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Editing Idea</h1>
   <%= render 'form', idea: @idea %>
  </div>
</div>

app/views/ideas/index.html.erb
<div class="home-banner" style="display: flex;">
  <div class="col-sm-6", style="display: flex; align-items: center; justify-content: center;">
  <%= render 'ideas/searchbar' %>
  </div>
  <div class="col-sm-6", style="display: flex; align-items: center; justify-content: center;">
    <div>
      <h1>Air Seed</h1>
      <h2><span id="banner-typed-text"></span></h2>
    </div>
  </div>
</div>

<div class="main-container">
  <div class="container">
    <p id="search-text"><%= pluralize @ideas.count, 'idea' %> for your search</p>
    <div class="row">
      <% @ideas.each do |idea| %>
        <div class="col-xs-12 col-sm-4">
          <%= render 'shared/card-new', idea: idea  %>
        </div>
      <% end %>
    </div>
  </div>
  <div
    id="map"
    style="width: 100%;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/ideas/new.html.erb
<div class="container">
  <div class="row">
   <%= render 'form', idea: @idea %>
  </div>
</div>

app/views/ideas/search.html.erb
<div class="main-container">
  <div class="container">
    <%= render 'ideas/searchform' %>
    <p><%= pluralize @ideas.count, 'idea' %> for your search</p>
    <div class="row">
      <% @ideas.each do |idea| %>
        <div class="col-xs-12 col-sm-4">
          <%= render 'shared/card-new', idea: idea  %>
        </div>
      <% end %>
    </div>
  </div>
  <div
    id="map"
    style="width: 100%;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/ideas/show.html.erb
<div class="container">
  <div class="flexline">
    <div class="main white-box">
      <h3><%= @idea.title %></h3>
      <%= cl_image_tag @idea.photo, height: 180, width: 180, crop: :fill %>
      <p><%= @idea.category %></p>
      <a class="navbar-wagon-item navbar-wagon-link" href="https://www.linkedin.com/in/elon-musk-899732174/" target="_blank"><%= @idea.user.first_name %> <%= @idea.user.last_name %></a>
      <a class="navbar-wagon-item navbar-wagon-link" href="https://www.linkedin.com/in/elon-musk-899732174/" target="_blank"><i class="fab fa-linkedin"></i>
      <br>
      <br>
      <br>
      <%= link_to "Book", new_idea_booking_path(@idea), class: "btn btn-primary btn-lg" %>
    </div>
    <div class="stats-and-description">
      <div class="stats-flexline">
        <div class="stat">
          <h3>Price per day</h3>
          <p><%= @idea.pricing %> €</p>
        </div>
        <div class="stat">
          <h3>Min. duration</h3>
          <p><%= pluralize @idea.minimum_duration, "day" %></p>
        </div>
        <div class="stat">
          <div
            id="map"
            class="small-map"
            data-markers="<%= @marker.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          ></div>
        </div>
      </div>
      <div class="description white-box">
        <h3>More about the idea</h3>
        <p> <%= @idea.description %> </p>
        <h3>Application Criteria</h3>
        <p><%= @idea.application_criteria %></p>
      </div>
    </div>
  </div>
    <div class="reviews">
      <div class="list-unstyled">
        <% @idea.reviews.each do |r| %>
        <div class="display-flex">
          <div>
            <ul class="rating text-center">
              <% r.rating.times do %><i class="fas fa-star"></i> <% end %>
            </ul>
          </div>
          <div>
              <i> <%= r.comment %> </i>
          </div>
        </div>
        <% end %>
      </div>
    </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/style.css">
    <title>airSeed</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('plant.png') %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="wrapper">
      <div class="border" style="width: 100%; height: 70px"></div>
      <%= render 'shared/navbar' %>
      <% if notice %>
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      <% end %>
     <% if alert %>
       <div class="alert alert-warning alert-dismissible" role="alert">
         <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
         <%= alert %>
       </div>
     <% end %>
      <%= render 'shared/modal' %>
      <%= yield %>
      <%= render 'shared/footer' %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <div class="formulairereview">
    <div class="principalerev Wwhite-box">
      <%= simple_form_for [@booking, @review] do |f| %>
        <p>Review</p>
        <%= f.input :comment %>
        <%= f.input :rating, as: :select, collection: 1..5%>
        <%= f.submit "add a review", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_avatar.html.erb
<% image = user.photo.blank? ? "admin_avatar.png" : user.photo.url %>
<%= image_tag image, class: "main-avatar", title: user.first_name %>

app/views/shared/_card.html.erb
  <% my_background = idea.photo.blank? ? "default.png" : idea.photo %>
  <%= link_to idea_path(idea) do %>
    <div class="card"
         style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
             url('<%= cl_image_path my_background, height: 300, width: 400, crop: :fill %>')"
    >
      <div class="card-category"><%= idea.title %></div>
        <div class="card-description">
          <p><%= idea.category %></p>
        </div>
      </div>
  <% end %>
`

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.linkedin.com/in/olivier-van-den-broek-93634a9/?originalSubdomain=fr"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/olivier-van-den-broek-93634a9/?originalSubdomain=fr"><i class="fab fa-instagram"></i></a>
    <a href="https://www.linkedin.com/in/olivier-van-den-broek-93634a9/?originalSubdomain=fr"><i class="fab fa-facebook"></i></a>
    <a href="https://www.linkedin.com/in/olivier-van-den-broek-93634a9/?originalSubdomain=fr"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/in/olivier-van-den-broek-93634a9/?originalSubdomain=fr"><i class="fab fa-linkedin"></i></a>
  </div>

  <p id="myBtn">Donate</p>

  <!-- The Modal -->


  <div class="footer-copyright">
    All rights reserved to Seed Inc
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top navbar-wagon-white">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "plant.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Home", ideas_path, class: "navbar-wagon-item navbar-wagon-link navbar-title" %>
    <%= link_to "Dashboard", users_show_path, class: "navbar-wagon-item navbar-wagon-link navbar-title" %>
    <%= link_to "I'm feeling creative", new_idea_path, class: "navbar-wagon-item navbar-wagon-link navbar-title" %>
    <%= link_to "Search", ideas_path, class: "navbar-wagon-item navbar-wagon-link navbar-title" %>
    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "admin_avatar.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown", title: current_user.email %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to users_show_path do %>
                <i class="fa fa-user"></i> Profile
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link navbar-title" %>
    <% end %>
    <!-- Avatar with dropdown menu -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/_bookings.html.erb
<div class="bookings-container">
  <div class="col-xs-12 bookings">
    <% bookings.each do |booking| %>
      <% booking_date = ((Time.now - booking.created_at) / 1.day).round %>
      <% days_left = ((booking.end_date - Time.now.to_date) / 1.day).round %>
      <% days =  (booking.end_date - booking.start_date).to_i %>
      <div class="booking">
        <div class="booking-picture">
          <%= render 'shared/picture', idea: booking.idea  %>
        </div>
        <div class="booking-title">
            <p class="small-title"><strong><%= booking.idea.title  %></strong></p>
        </div>
        <div class="booking-description">

          <% if booking.validated %>
            <p><%=
            "Only #{days_left} days left to change your world with this idea at the reasonable cost of $#{booking.idea.pricing * days}"
            %>
          <% elsif booking.validated.nil? %>
            <p><%=
            "Wait for #{booking.idea.user.first_name} to review your application"
            %>
          <% end %>
          </p>
        </div>
        <% if booking.validated %>
          <div class="booking-review">
            <%=  link_to("Review", new_booking_review_path(booking), class:"review-link") %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_requests.html.erb
<div class="requests-container">
  <div class="col-xs-12 requests">
    <% requests.each do |request| %>
      <% request_date = ((Time.now - request.created_at) / 1.day).round %>
      <% days =  (request.end_date - request.start_date).to_i %>
      <div class="request">
        <div class="request-title">
          <%= render 'shared/avatar', user: request.user  %>
          <div class="request-header">
            <div class="request-header-text">
              <% if request.validated == nil %>
                <p><strong><%= request.user.first_name  %></strong></p>
                <p> wants to book </p>
                <p class="neutral"> <%= request.idea.title %></p>
              <% elsif request.validated %>
                <p>You've </p>
                <p class="accepted">accepted</p>
                <p><strong><%= request.user.first_name  %></strong></p>
                <p>'s request for <%= request.idea.title %></p>
              <% else %>
                <p>You've </p>
                <p class="declined">declined</p>
                <p><strong><%= request.user.first_name  %></strong></p>
                <p>'s request for <%= request.idea.title %></p>
              <% end %>
            </div>
            <div class="request-details">
              <p><%= "#{request.start_date} - #{request.end_date}" %></p>
              <p><strong>
                $<%= request.idea.pricing * days %>
              </strong></p>
            </div>
          </div>
        </div>
        <div class="request-text">
          <p>
            <%= request.request_message  %>
          </p>
        </div>
        <% if request.validated == nil %>
          <div class="request-buttons">
            <div class="buttons">
              <%= link_to "Validate", accept_booking_path(request), method: :patch, class: "btn btn-xl btn-success"  %>
              <%= link_to "Decline", decline_booking_path(request), method: :patch, class: "btn btn-xl btn-danger"  %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>